/**
 * FICTIONAL sample data used only when you opt in with VITE_DEMO_DATA=true.
 * It exists so you can review the UI with a populated board before your
 * Supabase project has real rows. The app shows a banner whenever it's on,
 * and writes are disabled — nothing here is a real developer.
 */
const daysAgo = (days) => new Date(Date.now() - days * 86400000).toISOString();

export const DEMO_PROFILES = [
  {
    id: "demo-1",
    name: "Ada Nakato",
    title: "Full-stack React engineer",
    location: "Kampala, Uganda",
    bio: "I build fast dashboards and payment flows for fintech teams across East Africa. Comfortable owning a feature from schema to ship.",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL"],
    experience: "5+ years",
    hourly_rate: "$35 / hour",
    rating: 4.8,
    verified: true,
    featured: true,
    open_to_work: true,
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    whatsapp: "256700000001",
    email: "hello@example.com",
    created_at: daysAgo(4),
  },
  {
    id: "demo-2",
    name: "Brian Okello",
    title: "Mobile developer (Flutter)",
    location: "Nairobi, Kenya",
    bio: "Flutter apps for logistics and field teams. Offline-first sync, maps, and clean state management.",
    skills: ["Flutter", "Dart", "Firebase", "UI/UX"],
    experience: "4 years",
    hourly_rate: "$28 / hour",
    rating: 4.6,
    verified: true,
    featured: false,
    open_to_work: true,
    github: "https://github.com/",
    whatsapp: "256700000002",
    email: "hello@example.com",
    created_at: daysAgo(9),
  },
  {
    id: "demo-3",
    name: "Fatima Yusuf",
    title: "Backend & data engineer",
    location: "Remote",
    bio: "Postgres tuning, ETL pipelines and API design. I like unglamorous work that makes everything else fast.",
    skills: ["Python", "PostgreSQL", "Docker", "DevOps"],
    experience: "6 years",
    hourly_rate: "$45 / hour",
    rating: 4.9,
    verified: false,
    featured: true,
    open_to_work: false,
    github: "https://github.com/",
    email: "hello@example.com",
    created_at: daysAgo(15),
  },
  {
    id: "demo-4",
    name: "Sam Mwangi",
    title: "Frontend engineer",
    location: "Kigali, Rwanda",
    bio: "Design systems, accessibility and motion. I turn Figma files into interfaces people enjoy using.",
    skills: ["React", "Tailwind CSS", "TypeScript"],
    experience: "3 years",
    hourly_rate: "$25 / hour",
    rating: 4.4,
    verified: false,
    featured: false,
    open_to_work: true,
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
    whatsapp: "256700000004",
    email: "hello@example.com",
    created_at: daysAgo(21),
  },
  {
    id: "demo-5",
    name: "Grace Achieng",
    title: "AI & ML engineer",
    location: "Kampala, Uganda",
    bio: "Fine-tuning small language models for local languages, and shipping the APIs that serve them.",
    skills: ["Python", "PyTorch", "AI", "FastAPI"],
    experience: "4 years",
    hourly_rate: "$50 / hour",
    rating: 4.7,
    verified: true,
    featured: false,
    open_to_work: true,
    github: "https://github.com/",
    whatsapp: "256700000005",
    email: "hello@example.com",
    created_at: daysAgo(27),
  },
  {
    id: "demo-6",
    name: "Idris Hassan",
    title: "DevOps engineer",
    location: "Dar es Salaam, Tanzania",
    bio: "CI/CD, containers and observability. I make deploys boring and rollbacks instant.",
    skills: ["Docker", "Kubernetes", "DevOps", "Go"],
    experience: "7 years",
    hourly_rate: "$40 / hour",
    rating: 4.5,
    verified: false,
    featured: false,
    open_to_work: false,
    github: "https://github.com/",
    email: "hello@example.com",
    created_at: daysAgo(33),
  },
];

export const DEMO_PROJECTS = [
  {
    id: "demo-p1",
    user_id: "demo-1",
    author_name: "Ada Nakato",
    title: "Sente Payments Dashboard",
    description:
      "A merchant dashboard for tracking mobile-money settlements, with live reconciliation and CSV exports.",
    tags: ["Web", "React", "Supabase"],
    repo_url: "https://github.com/",
    live_url: "https://example.com",
    featured: true,
    created_at: daysAgo(6),
  },
  {
    id: "demo-p2",
    user_id: "demo-2",
    author_name: "Brian Okello",
    title: "Fleet Tracker (Flutter)",
    description:
      "Offline-first delivery app with route capture, proof-of-delivery photos and background sync.",
    tags: ["Mobile", "Flutter", "Firebase"],
    repo_url: "https://github.com/",
    featured: false,
    created_at: daysAgo(12),
  },
  {
    id: "demo-p3",
    user_id: "demo-3",
    author_name: "Fatima Yusuf",
    title: "Open ETL kit",
    description:
      "A small Python toolkit for scheduling Postgres-to-warehouse loads with typed configs and retries.",
    tags: ["Tooling", "Python", "Open Source"],
    repo_url: "https://github.com/",
    live_url: "https://example.com",
    featured: false,
    created_at: daysAgo(18),
  },
  {
    id: "demo-p4",
    user_id: "demo-5",
    author_name: "Grace Achieng",
    title: "Luganda speech classifier",
    description:
      "Fine-tuned wav2vec model for local-language command recognition, served behind a FastAPI endpoint.",
    tags: ["AI", "Python", "Open Source"],
    repo_url: "https://github.com/",
    featured: true,
    created_at: daysAgo(24),
  },
];

export const DEMO_JOBS = [
  {
    id: "demo-j1",
    title: "Senior React Engineer",
    company: "Msingi Labs",
    location: "Remote (East Africa)",
    type: "Contract",
    level: "Senior",
    budget: "$2,500 – $4,000 / month",
    skills: ["React", "TypeScript", "Supabase"],
    description:
      "We're rebuilding our lending portal. You'll own the dashboard front end end-to-end, working directly with our backend engineer.",
    contact_email: "hiring@example.com",
    created_at: daysAgo(2),
  },
  {
    id: "demo-j2",
    title: "Flutter Developer (field ops app)",
    company: "Tumaini Logistics",
    location: "Kampala, Uganda",
    type: "Part-time",
    level: "Mid-level",
    budget: "$1,200 / month",
    skills: ["Flutter", "Firebase", "Mobile"],
    description:
      "Build an offline-first companion app for our drivers: route capture, deliveries and daily summaries.",
    contact_email: "jobs@example.com",
    created_at: daysAgo(7),
  },
  {
    id: "demo-j3",
    title: "DevOps contractor",
    company: "Savanna Health",
    location: "Remote",
    type: "Freelance",
    level: "Lead",
    budget: "$60 / hour",
    skills: ["Docker", "Kubernetes", "DevOps"],
    description:
      "Harden our deployment pipeline: containerise two services, add staging environments and set up alerting.",
    contact_email: "people@example.com",
    created_at: daysAgo(11),
  },
];

/**
 * Fictional applications so the dashboard "Applications received" inbox can be
 * previewed with sample data. They belong to the demo jobs above.
 */
export const DEMO_APPLICATIONS = [
  {
    id: "demo-a1",
    job_id: "demo-j1",
    applicant_name: "Ada Nakato",
    applicant_email: "ada@example.com",
    portfolio_url: "https://example.com/ada",
    message:
      "I led the rebuild of a lending dashboard on React + Supabase last year, including the settlement reconciliation views. I can start within two weeks and I'm comfortable owning the front end end-to-end.",
    created_at: daysAgo(1),
  },
  {
    id: "demo-a2",
    job_id: "demo-j1",
    applicant_name: "Sam Mwangi",
    applicant_email: "sam@example.com",
    portfolio_url: "https://example.com/sam",
    message:
      "Design systems and accessibility are my focus, so the portal's component library is the part that excites me most. Portfolio includes three dashboards shipped to production.",
    created_at: daysAgo(2),
  },
  {
    id: "demo-a3",
    job_id: "demo-j3",
    applicant_name: "Idris Hassan",
    applicant_email: "idris@example.com",
    portfolio_url: "https://example.com/idris",
    message:
      "I have moved four products from hand-rolled deploys to containerised pipelines, two of them in health. Happy to start with an audit and a staging environment in the first two weeks.",
    created_at: daysAgo(4),
  },
];
