import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { resolve, relative } from "node:path";

/**
 * Build-time plugins that finish the deployment story for `dist/`:
 *
 *  1. `seoFiles()`      — rewrites sitemap.xml / robots.txt to absolute URLs
 *                         when the deployment knows its origin.
 *  2. `serviceWorker()` — emits sw.js with a precache list generated from the
 *                         actual hashed bundle, and rewrites the web app
 *                         manifest for sub-path hosting.
 *
 * Everything here is production-only: the dev server is untouched.
 */

const stripTrailing = (value) => value.replace(/\/+$/, "");

/** Reads every emitted file under `dist`, relative to it. */
function listDistFiles(dir, base = dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = resolve(dir, entry);
    if (statSync(full).isDirectory()) return listDistFiles(full, base);
    return [relative(base, full).split("\\").join("/")];
  });
}

export function seoFiles() {
  return {
    name: "programmers-hub:seo-files",
    apply: "build",
    closeBundle() {
      const outDir = resolve(process.cwd(), "dist");
      const origin = stripTrailing(process.env.VITE_SITE_URL || "");
      if (!origin) return; // nothing absolute to write — keep the shipped files

      const base = process.env.VITE_BASE || "/";
      const prefix = `${origin}${stripTrailing(base)}`;
      const lastmod = new Date().toISOString().slice(0, 10);
      const sitemapPath = resolve(outDir, "sitemap.xml");
      const robotsPath = resolve(outDir, "robots.txt");

      if (existsSync(sitemapPath)) {
        writeFileSync(
          sitemapPath,
          readFileSync(sitemapPath, "utf8")
            .replace(/<loc>(\/[^<]*)<\/loc>/g, (_, path) => `<loc>${prefix}${path}</loc>`)
            .replace(/<changefreq>/g, `<lastmod>${lastmod}</lastmod><changefreq>`)
        );
      }

      if (existsSync(robotsPath)) {
        writeFileSync(
          robotsPath,
          readFileSync(robotsPath, "utf8").replace(/^Sitemap: .*$/m, `Sitemap: ${prefix}/sitemap.xml`)
        );
      }
    },
  };
}

/** Files worth caching up-front: the shell + the bundle + icons. */
const PRECACHE_PATTERNS = [
  /\.html$/,
  /assets\/.*\.(js|css|woff2?)$/,
  /(favicon\.svg|icon-\d+\.png|apple-touch-icon\.png|manifest\.webmanifest)$/,
];

const SW_TEMPLATE = `/* Generated by vite.config.js — do not edit by hand. */
const CACHE = "ph-shell-__VERSION__";
const ROOT = "__ROOT__";
const PRECACHE = __PRECACHE__;

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // allSettled: one 404 must never block the whole install.
      await Promise.allSettled(PRECACHE.map((url) => cache.add(new Request(url, { cache: "reload" }))));
      await self.skipWaiting();
    })()
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys.filter((key) => key.startsWith("ph-shell-") && key !== CACHE).map((key) => caches.delete(key))
      );
      await self.clients.claim();
    })()
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  // Same-origin only: Supabase, fonts and avatar CDNs are never intercepted.
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirst(request));
    return;
  }

  if (PRECACHE.includes(url.pathname)) event.respondWith(cacheFirst(request));
});

/** Fresh HTML whenever the network answers; the cached shell when it does not. */
async function networkFirst(request) {
  const cache = await caches.open(CACHE);
  try {
    const response = await fetch(request);
    if (response && response.ok) {
      await cache.put(new Request(ROOT), response.clone());
      return response;
    }
    return response;
  } catch {
    const cached = (await cache.match(new Request(ROOT))) || (await cache.match(request));
    if (cached) return cached;
    return new Response("<h1>Offline</h1><p>Reconnect to load Programmer's Hub.</p>", {
      status: 503,
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  }
}

/** Hashed assets are immutable, so cache first and refresh in the background. */
async function cacheFirst(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request);
  if (cached) return cached;

  const response = await fetch(request);
  if (response && response.ok && response.type === "basic") {
    await cache.put(request, response.clone());
  }
  return response;
}
`;

export function serviceWorker() {
  return {
    name: "programmers-hub:service-worker",
    apply: "build",
    closeBundle() {
      const outDir = resolve(process.cwd(), "dist");
      const base = process.env.VITE_BASE || "/";
      const root = base.endsWith("/") ? base : `${base}/`;

      const files = listDistFiles(outDir).filter((file) => file !== "sw.js");
      const precache = files
        .filter((file) => PRECACHE_PATTERNS.some((pattern) => pattern.test(file)))
        .map((file) => `${root}${root.endsWith("/") ? "" : "/"}${file}`.replace(/([^:]\/)\/+/g, "$1"));

      // Cache name changes whenever the bundle does, which retires stale assets.
      const version = String(
        files.reduce((hash, file) => (hash * 31 + file.length + file.charCodeAt(0)) % 1e9, 7)
      );

      writeFileSync(
        resolve(outDir, "sw.js"),
        SW_TEMPLATE.replace("__VERSION__", version)
          .replace("__ROOT__", root)
          .replace("__PRECACHE__", JSON.stringify(precache, null, 2))
      );

      // Sub-path hosting: make the manifest point at the real scope.
      const manifestPath = resolve(outDir, "manifest.webmanifest");
      if (existsSync(manifestPath) && root !== "/") {
        const manifest = readFileSync(manifestPath, "utf8").replace(
          /"(src|start_url|url|scope)":\s*"\/([^"]*)"/g,
          (_, key, path) => `"${key}": "${root}${path}"`
        );
        writeFileSync(manifestPath, manifest);
      }
    },
  };
}
